import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Ordered by hand, not autogenerated: the sequence is the argument.
 *
 * "Why Catalyst" sits above every category because the first question a visitor
 * has is not how to install something — it is what this is and why it exists.
 *
 * Generated API reference, when it lands, should use `autogenerated` so it
 * mirrors the code without manual upkeep.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    "why-catalyst",
    {
      type: "category",
      label: "How Catalyst works",
      collapsed: false,
      items: ["how-it-works/architecture",
        "how-it-works/offline-sync",
        "how-it-works/data-flow",],
    },
    {
      type: "category",
      label: "AI-assisted development",
      collapsed: false,
      items: ["ai/how-it-fits", "ai/the-skills", "ai/trust-and-verify"],
    },
    {
      type: "category",
      label: "Build",
      collapsed: false,
      items: [
        "build/quickstart",
        "build/the-workspace",
        "build/design-system-setup",
        "build/your-first-feature",
        "build/writes-and-the-outbox",
        "build/components-and-tokens",
      ],
    },
    {
      type: "category",
      label: "Ship to native",
      collapsed: false,
      items: [
        "ship-to-native/the-migration",
        "ship-to-native/what-web-qa-cannot-catch",
        "ship-to-native/release",
      ],
    },
    "troubleshooting",
  ],
};

export default sidebars;
