import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The prose sidebar is ordered by hand rather than autogenerated: reading order is
 * the point of this section and does not follow filesystem or alphabetical order.
 *
 * Generated API reference, when it lands, should use `autogenerated` instead so it
 * mirrors the code without manual upkeep.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/what-is-catalyst",
        "getting-started/quickstart",
        "getting-started/what-am-i-looking-at",
        "getting-started/build-your-first-feature",
      ],
    },
  ],
};

export default sidebars;
